site_name: Arm Keil Studio for VS Code
repo_name: GitHub
repo_url: https://github.com/MDK-Packs/vscode-cmsis-solution-docs
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Installation: installation.md
    - User interface: userinterface.md
    - Work with Solutions: create_app.md
    - Manage solutions: manage_settings.md
    - Software components: manage_components.md
    - Debug: debug.md
    - Configuration: configuration.md
    - Import uVision projects: importuv.md
    - Run external tools: runexternal.md
    - Tips and tricks: tipsandtricks.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
use_directory_urls: false
