site_name: Arm Keil Studio for VS Code
extra: 
  version: 1.64.0
repo_name: GitHub
repo_url: https://github.com/MDK-Packs/vscode-cmsis-solution-docs
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Installation: installation.md
    - User interface: userinterface.md
    - Work with CMSIS solutions: create_app.md
    - Work with Zephyr applications: zephyr.md
    - Manage solutions: manage_settings.md
    - Build and run: build_run.md
    - Debug: debug.md
    - Import uVision projects: importuv.md
    - Run external tools: runexternal.md
    - Tips and tricks: tipsandtricks.md
    - Read further: read_further.md
    - Features and roadmap: featureroadmap.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
use_directory_urls: false
